import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Providers from "./providers";
import Header from "@/components/header";
import { getServerSession } from "next-auth";
import "./globals.css";
import "react-image-crop/dist/ReactCrop.css";
import { authOptions } from "./api/auth/[...nextauth]/authOptions";
import { ReactNode } from "react";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "700"], // Specify weights as needed
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en" className="dark">
      <body className={`${roboto.variable} antialiased`}>
        <Providers session={session}>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
